# Generated by Django 4.2.3 on 2023-07-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KurzFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_pictures',
            name='image',
            field=models.ImageField(upload_to='KurzFinalApp/templates/dog_images'),
        ),
    ]
